Adiconado informacoes sobre a vida em Alkmaar (cidade)
brazil-tech-expats/wiki pull request #11
Opened 2018-10-04 15:58 UTC by paulovitorbal

2018-10-04 16:39 UTC, djalmaaraujo requested changes

2018-10-04 16:39 UTC, djalmaaraujo commented on countries/netherlands.md
> +<<<<<<< HEAD
can you remove this?

2018-10-04 16:39 UTC, djalmaaraujo commented on countries/netherlands.md
> +>>>>>>> c37873ecdb23f16d21ab65027807399522145b3a
can you remove this?

2018-10-05 15:05 UTC, paulovitorbal reviewed
done

2018-10-05 15:08 UTC, djalmaaraujo commented
@paulovitorbal Seu branch possui conflitos com o master. Você precisa resolvê-los para que possamos mergear.

2018-10-05 15:15 UTC, djalmaaraujo commented
@paulovitorbal 
![image 2018-10-05 at 4 14 25 pm](https://user-images.githubusercontent.com/3402/46543840-d0a85d80-c8b9-11e8-9fbf-3ea446089f5b.png)

2018-10-05 15:20 UTC, paulovitorbal commented
![image](https://user-images.githubusercontent.com/1259996/46544118-0271f200-c8c3-11e8-8eb2-71bf34679bf7.png)

2018-10-05 15:47 UTC, djalmaaraujo commented
@paulovitorbal Você precisa dar rebase do seu branch com o master, merge não vai adiantar.

2018-10-05 15:48 UTC, merged

2018-10-05 15:50 UTC, djalmaaraujo commented
@paulovitorbal Acho que foi, confere lá. Obrigado